###################################################
##### SHAFT_Engine: TestNG.properties
###################################################
setParallel=METHODS
setThreadCount=1
setVerbose=1
setPreserveOrder=true
setGroupByInstances=true

###################################################
##### END of PropertiesHelper File
###################################################